// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: account.proto

package corepb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ContractAuthority struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	AccessType           string   `protobuf:"bytes,3,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractAuthority) Reset()         { *m = ContractAuthority{} }
func (m *ContractAuthority) String() string { return proto.CompactTextString(m) }
func (*ContractAuthority) ProtoMessage()    {}
func (*ContractAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}
func (m *ContractAuthority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractAuthority.Unmarshal(m, b)
}
func (m *ContractAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractAuthority.Marshal(b, m, deterministic)
}
func (m *ContractAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractAuthority.Merge(m, src)
}
func (m *ContractAuthority) XXX_Size() int {
	return xxx_messageInfo_ContractAuthority.Size(m)
}
func (m *ContractAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_ContractAuthority proto.InternalMessageInfo

func (m *ContractAuthority) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ContractAuthority) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ContractAuthority) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

type Permission struct {
	AuthCategory         string   `protobuf:"bytes,1,opt,name=auth_category,json=authCategory,proto3" json:"auth_category,omitempty"`
	AuthMessage          [][]byte `protobuf:"bytes,2,rep,name=auth_message,json=authMessage,proto3" json:"auth_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}
func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetAuthCategory() string {
	if m != nil {
		return m.AuthCategory
	}
	return ""
}

func (m *Permission) GetAuthMessage() [][]byte {
	if m != nil {
		return m.AuthMessage
	}
	return nil
}

type Contract struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Methods              []string `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}
func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Contract) GetMethods() []string {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *Contract) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Account struct {
	Address              []byte        `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              []byte        `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	FrozenFund           []byte        `protobuf:"bytes,3,opt,name=frozen_fund,json=frozenFund,proto3" json:"frozen_fund,omitempty"`
	PledgeFund           []byte        `protobuf:"bytes,4,opt,name=pledge_fund,json=pledgeFund,proto3" json:"pledge_fund,omitempty"`
	Nonce                uint64        `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	VarsHash             []byte        `protobuf:"bytes,6,opt,name=vars_hash,json=varsHash,proto3" json:"vars_hash,omitempty"`
	CreditIndex          []byte        `protobuf:"bytes,7,opt,name=credit_index,json=creditIndex,proto3" json:"credit_index,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,8,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *Account) GetFrozenFund() []byte {
	if m != nil {
		return m.FrozenFund
	}
	return nil
}

func (m *Account) GetPledgeFund() []byte {
	if m != nil {
		return m.PledgeFund
	}
	return nil
}

func (m *Account) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Account) GetVarsHash() []byte {
	if m != nil {
		return m.VarsHash
	}
	return nil
}

func (m *Account) GetCreditIndex() []byte {
	if m != nil {
		return m.CreditIndex
	}
	return nil
}

func (m *Account) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*ContractAuthority)(nil), "corepb.ContractAuthority")
	proto.RegisterType((*Permission)(nil), "corepb.Permission")
	proto.RegisterType((*Contract)(nil), "corepb.Contract")
	proto.RegisterType((*Account)(nil), "corepb.Account")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x8b, 0xdb, 0x30,
	0x10, 0xc5, 0x71, 0xfe, 0xd8, 0xf1, 0xd8, 0x39, 0x54, 0x94, 0x22, 0xe8, 0xa1, 0xae, 0x7b, 0xf1,
	0x29, 0x87, 0xb6, 0x5f, 0x20, 0x04, 0x4a, 0x7b, 0x28, 0x2c, 0x22, 0x87, 0xbd, 0x19, 0x45, 0x9e,
	0xc4, 0x86, 0x44, 0x32, 0x92, 0x1c, 0xd6, 0xfb, 0x15, 0xf6, 0x4b, 0x2f, 0x92, 0xe2, 0xdd, 0x3d,
	0xe5, 0xf8, 0x7e, 0x33, 0x7e, 0x7e, 0x3c, 0x0d, 0xac, 0xb9, 0x10, 0x6a, 0x90, 0x76, 0xd3, 0x6b,
	0x65, 0x15, 0x89, 0x85, 0xd2, 0xd8, 0x1f, 0xca, 0x23, 0x7c, 0xda, 0x29, 0x69, 0x35, 0x17, 0x76,
	0x3b, 0xd8, 0x56, 0xe9, 0xce, 0x8e, 0x84, 0x42, 0xc2, 0x9b, 0x46, 0xa3, 0x31, 0x34, 0x2a, 0xa2,
	0x2a, 0x67, 0x93, 0x24, 0x5f, 0x20, 0xbe, 0xa0, 0x6d, 0x55, 0x43, 0x67, 0x45, 0x54, 0xa5, 0xec,
	0xa6, 0xc8, 0x37, 0xc8, 0xb8, 0x10, 0x68, 0x4c, 0x6d, 0xc7, 0x1e, 0xe9, 0xdc, 0x0f, 0x21, 0xa0,
	0xfd, 0xd8, 0x63, 0xb9, 0x07, 0x78, 0x40, 0x7d, 0xe9, 0x8c, 0xe9, 0x94, 0x24, 0x3f, 0x60, 0xcd,
	0x07, 0xdb, 0xd6, 0x82, 0x5b, 0x3c, 0x29, 0x3d, 0xfa, 0xdf, 0xa4, 0x2c, 0x77, 0x70, 0x77, 0x63,
	0xe4, 0x3b, 0x78, 0x5d, 0x5f, 0xd0, 0x18, 0x7e, 0x42, 0x3a, 0x2b, 0xe6, 0x55, 0xce, 0x32, 0xc7,
	0xfe, 0x07, 0x54, 0x3e, 0xc2, 0x6a, 0x4a, 0x7f, 0x27, 0x34, 0x85, 0x24, 0xc4, 0x34, 0xde, 0x23,
	0x65, 0x93, 0x74, 0x93, 0x2b, 0x6a, 0x17, 0xe9, 0x16, 0x79, 0x92, 0xe5, 0xcb, 0x0c, 0x92, 0x6d,
	0x68, 0xec, 0xbe, 0xf3, 0x81, 0x9f, 0xb9, 0x14, 0xe8, 0xfb, 0xc8, 0xd9, 0x24, 0x5d, 0x21, 0x47,
	0xad, 0x9e, 0x51, 0xd6, 0xc7, 0x41, 0x36, 0xde, 0x3d, 0x67, 0x10, 0xd0, 0x9f, 0x41, 0xfa, 0xc6,
	0xfa, 0x33, 0x36, 0x27, 0x0c, 0x0b, 0x8b, 0xb0, 0x10, 0x90, 0x5f, 0xf8, 0x0c, 0x4b, 0xa9, 0x9c,
	0xf3, 0xb2, 0x88, 0xaa, 0x05, 0x0b, 0x82, 0x7c, 0x85, 0xf4, 0xca, 0xb5, 0xa9, 0x5b, 0x6e, 0x5a,
	0x1a, 0xfb, 0x8f, 0x56, 0x0e, 0xfc, 0xe5, 0xa6, 0x75, 0x8d, 0x09, 0x8d, 0x4d, 0x67, 0xeb, 0x4e,
	0x36, 0xf8, 0x44, 0x13, 0x3f, 0xcf, 0x02, 0xfb, 0xe7, 0x10, 0xf9, 0x0d, 0x59, 0xff, 0xf6, 0x0e,
	0x86, 0xae, 0x8a, 0x79, 0x95, 0xfd, 0x24, 0x9b, 0x70, 0x0d, 0x9b, 0xf7, 0x27, 0x62, 0x1f, 0xd7,
	0x0e, 0xb1, 0x3f, 0x9a, 0x5f, 0xaf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x24, 0xaf, 0x07, 0xde, 0x45,
	0x02, 0x00, 0x00,
}
